facebook:
  client:
    clientId: 414665505536880
    clientSecret: e85a30ea55b5c775fa8565a76df70987
    accessTokenUri: https://graph.facebook.com/oauth/access_token
    userAuthorizationUri: https://www.facebook.com/dialog/oauth
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://graph.facebook.com/me

github:
  client:
    clientId: 1ed84cede28feb9d8d2b
    clientSecret: 29a21404982ced497433c2eed92f9d3d249b356a
    accessTokenUri: https://github.com/login/oauth/access_token
    userAuthorizationUri: https://github.com/login/oauth/authorize
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://api.github.com/user

spring:
  application:
    name: SocialMediaWiki
  profiles:
      # The commented value for `active` can be replaced with valid spring profiles to load.
      # Otherwise, it will be filled in by maven when building the WAR file
      # Either way, it can be overridden by `--spring.profiles.active` value passed in the commandline or `-Dspring.profiles.active` set in `JAVA_OPTS`
      active: prod

  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: validate

  datasource:
    url: jdbc:mysql://sql9.freemysqlhosting.net:3306/sql9162980
    username: sql9162980
    password: J2R6nwV4ZY
    driver-class-name: com.mysql.jdbc.Driver